<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>DocumentFlow.Infrastructure</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="..\DocumentFlow.Application\DocumentFlow.Application.csproj"/><ProjectReference Include="..\DocumentFlow.Domain\DocumentFlow.Domain.csproj"/><PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference><PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11"/><PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.11"/><PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1"/></ItemGroup></Project>

